# ************************************************************************* #
#                                                                           #
#                                                      :::      ::::::::    #
#  argument_parser.py                                :+:      :+:    :+:    #
#                                                  +:+ +:+         +:+      #
#  By: anacharp, roandrie                        +#+  +:+       +#+         #
#                                              +#+#+#+#+#+   +#+            #
#  Created: 2026/05/14 17:42:52 by roandrie        #+#    #+#               #
#  Updated: 2026/06/12 12:14:44 by anacharp        ###   ########.fr        #
#                                                                           #
# ************************************************************************* #

from typing import NoReturn

import sys
import argparse

from src.utils import print_error
from src.config import load_config


class RichArgumentParser(argparse.ArgumentParser):
    """
    Custom ArgumentParser that leverages Rich for enhanced error reporting.

    This class overrides the default error handling to ensure all CLI errors
    are displayed using the project's styled output utilities.
    """

    def error(self, message: str) -> NoReturn:
        """
        Handle parsing errors by displaying a styled message and exiting.

        Args:
            message (str): The error message generated by argparse.
        Raises:
            SystemExit: Always raised with code 2 to abort executing contexts.
        """
        print_error(message)
        self.print_usage(sys.stderr)
        sys.exit(2)


def load_arguments() -> argparse.Namespace:
    """Configures systemic rules and parses string arguments from execution
    arrays.

    Maps structural parameters including system paths to JSON configs alongside
    boolean toggles handling developer flags.

    Returns:
        argparse.Namespace: Object container wrapping verified runtime
        configurations.
    """

    # Create the parser object
    parser: RichArgumentParser = RichArgumentParser(
        prog="Pac-Man",
        description=("Recreation of the famous arcade game: Pac-Man"),
        usage=("python3 pac-man.py data/config.json"),
        epilog=" ",
        formatter_class=argparse.RawTextHelpFormatter
    )

    # Add the config argument
    parser.add_argument(
        "config_file",
        help=("path where config in json of the game is stored.\n"
              "default: data/config.json"),
        metavar="config.json",
        type=load_config
    )

    parser.add_argument(
        "-d", "--debug",
        help="launch with the debug mode (for dev)",
        required=False,
        action="store_true"
    )

    args: argparse.Namespace = parser.parse_args()

    return args
