# ************************************************************************* #
#                                                                           #
#                                                      :::      ::::::::    #
#  argument_parser.py                                :+:      :+:    :+:    #
#                                                  +:+ +:+         +:+      #
#  By: anacharp, roandrie                        +#+  +:+       +#+         #
#                                              +#+#+#+#+#+   +#+            #
#  Created: 2026/05/14 17:42:52 by roandrie        #+#    #+#               #
#  Updated: 2026/05/15 09:30:56 by roandrie        ###   ########.fr        #
#                                                                           #
# ************************************************************************* #

from typing import NoReturn

import sys
import argparse

from src.utils import print_error


class RichArgumentParser(argparse.ArgumentParser):
    """
    Custom ArgumentParser that leverages Rich for enhanced error reporting.

    This class overrides the default error handling to ensure all CLI errors
    are displayed using the project's styled output utilities.
    """

    def error(self, message: str) -> NoReturn:
        """
        Handle parsing errors by displaying a styled message and exiting.

        Args:
            message (str): The error message generated by argparse.
        """
        print_error(message)
        self.print_usage(sys.stderr)
        sys.exit(2)


def load_arguments() -> None:
    pass

    # only 1 argument accepted "config.json"
    # check if correct, and load it with config_loader
    # debug mode for dev only
    # check if leaderboard file exist
    # if everything ok, return all object
